DROP TABLE IF EXISTS `address`;
CREATE TABLE `address` (
  `addrId` int NOT NULL AUTO_INCREMENT,
  `street` varchar(30) NOT NULL,
  `city` varchar(30) NOT NULL,
  `state` varchar(30) NOT NULL,
  PRIMARY KEY (`addrId`)
);
insert into address (addrId, street, city, state) values (1, '9608 Annamark Avenue', 'Palo Alto', 'CA');
insert into address (addrId, street, city, state) values (2, '70736 Sommers Way', 'Bradenton', 'FL');
insert into address (addrId, street, city, state) values (3, '6709 Hayes Park', 'Glendale', 'AZ');
insert into address (addrId, street, city, state) values (4, '768 Hermina Alley', 'Columbus', 'OH');
insert into address (addrId, street, city, state) values (5, '9128 Lake View Lane', 'Milwaukee', 'WI');
insert into address (addrId, street, city, state) values (6, '1528 Manufacturers Terrace', 'Pensacola', 'FL');
insert into address (addrId, street, city, state) values (7, '394 Saint Paul Point', 'Mesa', 'AZ');
insert into address (addrId, street, city, state) values (8, '3 Karstens Crossing', 'Savannah', 'GA');
insert into address (addrId, street, city, state) values (9, '684 Weeping Birch Plaza', 'Buffalo', 'NY');
insert into address (addrId, street, city, state) values (10, '0729 Lotheville Street', 'Charlotte', 'NC');
insert into address (addrId, street, city, state) values (11, '62385 Pierstorff Drive', 'Clearwater', 'FL');
insert into address (addrId, street, city, state) values (12, '4 Lakeland Park', 'Akron', 'OH');
insert into address (addrId, street, city, state) values (13, '77401 Meadow Ridge Avenue', 'Baltimore', 'MD');
insert into address (addrId, street, city, state) values (14, '80249 Ryan Parkway', 'Portsmouth', 'VA');
insert into address (addrId, street, city, state) values (15, '83174 Johnson Crossing', 'Springfield', 'MO');
insert into address (addrId, street, city, state) values (16, '2 Bellgrove Place', 'Great Neck', 'NY');
insert into address (addrId, street, city, state) values (17, '3963 Logan Point', 'Flint', 'MI');
insert into address (addrId, street, city, state) values (18, '4005 Ryan Alley', 'Topeka', 'KS');
insert into address (addrId, street, city, state) values (19, '59 Blue Bill Park Pass', 'Columbia', 'SC');
insert into address (addrId, street, city, state) values (20, '80699 Hallows Point', 'Phoenix', 'AZ');
insert into address (addrId, street, city, state) values (21, '5113 Boyd Hill', 'Fairfax', 'VA');
insert into address (addrId, street, city, state) values (22, '8680 Golf Course Park', 'Fayetteville', 'NC');
insert into address (addrId, street, city, state) values (23, '61 Corben Terrace', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (24, '5839 Tennessee Alley', 'Amarillo', 'TX');
insert into address (addrId, street, city, state) values (25, '38295 John Wall Hill', 'Irving', 'TX');
insert into address (addrId, street, city, state) values (26, '22998 Knutson Pass', 'Hartford', 'CT');
insert into address (addrId, street, city, state) values (27, '48 Maywood Plaza', 'Atlanta', 'GA');
insert into address (addrId, street, city, state) values (28, '477 Petterle Park', 'Athens', 'GA');
insert into address (addrId, street, city, state) values (29, '8 Tony Pass', 'Phoenix', 'AZ');
insert into address (addrId, street, city, state) values (30, '39244 Carberry Point', 'Savannah', 'GA');
insert into address (addrId, street, city, state) values (31, '781 Union Junction', 'Birmingham', 'AL');
insert into address (addrId, street, city, state) values (32, '04 Pawling Drive', 'San Antonio', 'TX');
insert into address (addrId, street, city, state) values (33, '5268 Rusk Plaza', 'Yakima', 'WA');
insert into address (addrId, street, city, state) values (34, '20580 Bonner Avenue', 'Pueblo', 'CO');
insert into address (addrId, street, city, state) values (35, '511 Mifflin Alley', 'Indianapolis', 'IN');
insert into address (addrId, street, city, state) values (36, '574 Kennedy Pass', 'Bronx', 'NY');
insert into address (addrId, street, city, state) values (37, '82 Hooker Park', 'Houston', 'TX');
insert into address (addrId, street, city, state) values (38, '01 Moland Terrace', 'Troy', 'MI');
insert into address (addrId, street, city, state) values (39, '09755 4th Trail', 'Lincoln', 'NE');
insert into address (addrId, street, city, state) values (40, '66992 Meadow Vale Court', 'Houston', 'TX');
insert into address (addrId, street, city, state) values (41, '199 Trailsway Plaza', 'Toledo', 'OH');
insert into address (addrId, street, city, state) values (42, '1704 Kennedy Circle', 'Roanoke', 'VA');
insert into address (addrId, street, city, state) values (43, '1 Clarendon Alley', 'Spring', 'TX');
insert into address (addrId, street, city, state) values (44, '178 Miller Point', 'Brooklyn', 'NY');
insert into address (addrId, street, city, state) values (45, '44217 Sauthoff Drive', 'El Paso', 'TX');
insert into address (addrId, street, city, state) values (46, '8 Anzinger Trail', 'Grand Rapids', 'MI');
insert into address (addrId, street, city, state) values (47, '6750 Summit Way', 'Redwood City', 'CA');
insert into address (addrId, street, city, state) values (48, '26913 Eagan Point', 'El Paso', 'TX');
insert into address (addrId, street, city, state) values (49, '9919 5th Street', 'Levittown', 'PA');
insert into address (addrId, street, city, state) values (50, '66611 Northwestern Court', 'Cumming', 'GA');
insert into address (addrId, street, city, state) values (51, '7053 Oxford Road', 'Santa Fe', 'NM');
insert into address (addrId, street, city, state) values (52, '1 Manufacturers Crossing', 'Phoenix', 'AZ');
insert into address (addrId, street, city, state) values (53, '6 Melby Court', 'San Diego', 'CA');
insert into address (addrId, street, city, state) values (54, '5236 Katie Park', 'Oklahoma City', 'OK');
insert into address (addrId, street, city, state) values (55, '73 Marquette Lane', 'Sioux Falls', 'SD');
insert into address (addrId, street, city, state) values (56, '3340 Surrey Drive', 'Mobile', 'AL');
insert into address (addrId, street, city, state) values (57, '69 Susan Plaza', 'Jacksonville', 'FL');
insert into address (addrId, street, city, state) values (58, '63 Texas Pass', 'Columbus', 'GA');
insert into address (addrId, street, city, state) values (59, '915 Fremont Road', 'Portland', 'ME');
insert into address (addrId, street, city, state) values (60, '7274 Debs Crossing', 'Brooklyn', 'NY');
insert into address (addrId, street, city, state) values (61, '31569 Atwood Pass', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (62, '8560 Autumn Leaf Way', 'North Little Rock', 'AR');
insert into address (addrId, street, city, state) values (63, '19427 Jay Avenue', 'Montgomery', 'AL');
insert into address (addrId, street, city, state) values (64, '38817 Northridge Parkway', 'Houston', 'TX');
insert into address (addrId, street, city, state) values (65, '09143 Fieldstone Hill', 'Ridgely', 'MD');
insert into address (addrId, street, city, state) values (66, '17888 Harbort Drive', 'Phoenix', 'AZ');
insert into address (addrId, street, city, state) values (67, '8 Kensington Lane', 'Saint Paul', 'MN');
insert into address (addrId, street, city, state) values (68, '39504 Briar Crest Way', 'Yonkers', 'NY');
insert into address (addrId, street, city, state) values (69, '8 Farragut Drive', 'Saint Louis', 'MO');
insert into address (addrId, street, city, state) values (70, '5 Kennedy Pass', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (71, '115 Hagan Avenue', 'Denver', 'CO');
insert into address (addrId, street, city, state) values (72, '046 Columbus Way', 'Saint Paul', 'MN');
insert into address (addrId, street, city, state) values (73, '4551 Lakewood Gardens Parkway', 'Montgomery', 'AL');
insert into address (addrId, street, city, state) values (74, '51788 Mayer Court', 'Vancouver', 'WA');
insert into address (addrId, street, city, state) values (75, '9568 Portage Point', 'Wilkes Barre', 'PA');
insert into address (addrId, street, city, state) values (76, '76151 Sage Place', 'Garden Grove', 'CA');
insert into address (addrId, street, city, state) values (77, '414 Rieder Road', 'Reading', 'PA');
insert into address (addrId, street, city, state) values (78, '71107 Merry Junction', 'Santa Rosa', 'CA');
insert into address (addrId, street, city, state) values (79, '44212 Lawn Street', 'Winter Haven', 'FL');
insert into address (addrId, street, city, state) values (80, '9 Eastwood Junction', 'Waterbury', 'CT');
insert into address (addrId, street, city, state) values (81, '019 Roth Way', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (82, '97 Becker Way', 'Philadelphia', 'PA');
insert into address (addrId, street, city, state) values (83, '5564 Kim Road', 'Omaha', 'NE');
insert into address (addrId, street, city, state) values (84, '881 Bunting Alley', 'El Paso', 'TX');
insert into address (addrId, street, city, state) values (85, '2 Magdeline Junction', 'Moreno Valley', 'CA');
insert into address (addrId, street, city, state) values (86, '6 Butterfield Center', 'Anchorage', 'AK');
insert into address (addrId, street, city, state) values (87, '12467 Calypso Junction', 'Riverside', 'CA');
insert into address (addrId, street, city, state) values (88, '96289 Maryland Park', 'Houston', 'TX');
insert into address (addrId, street, city, state) values (89, '3202 Lukken Drive', 'Los Angeles', 'CA');
insert into address (addrId, street, city, state) values (90, '2 Elmside Junction', 'Reno', 'NV');
insert into address (addrId, street, city, state) values (91, '045 Glendale Avenue', 'Oklahoma City', 'OK');
insert into address (addrId, street, city, state) values (92, '057 Sutherland Terrace', 'Miami', 'FL');
insert into address (addrId, street, city, state) values (93, '501 Oak Way', 'Saint Petersburg', 'FL');
insert into address (addrId, street, city, state) values (94, '01373 3rd Park', 'Erie', 'PA');
insert into address (addrId, street, city, state) values (95, '56428 Corben Street', 'Fort Lauderdale', 'FL');
insert into address (addrId, street, city, state) values (96, '95143 Dahle Park', 'Wichita', 'KS');
insert into address (addrId, street, city, state) values (97, '576 Kenwood Terrace', 'Fort Worth', 'TX');
insert into address (addrId, street, city, state) values (98, '03249 Alpine Avenue', 'Gilbert', 'AZ');
insert into address (addrId, street, city, state) values (99, '96943 Waxwing Street', 'Cedar Rapids', 'IA');
insert into address (addrId, street, city, state) values (100, '735 Linden Avenue', 'San Angelo', 'TX');
insert into address (addrId, street, city, state) values (101, '92 Eastlawn Terrace', 'Buffalo', 'NY');
insert into address (addrId, street, city, state) values (102, '64776 Del Sol Crossing', 'Lexington', 'KY');
insert into address (addrId, street, city, state) values (103, '58672 Sage Parkway', 'Miami', 'FL');
insert into address (addrId, street, city, state) values (104, '4088 Algoma Parkway', 'Racine', 'WI');
insert into address (addrId, street, city, state) values (105, '6715 Corry Avenue', 'Columbia', 'SC');
insert into address (addrId, street, city, state) values (106, '97 Stoughton Junction', 'Winter Haven', 'FL');
insert into address (addrId, street, city, state) values (107, '85 Del Sol Center', 'Idaho Falls', 'ID');
insert into address (addrId, street, city, state) values (108, '072 Nobel Avenue', 'Irvine', 'CA');
insert into address (addrId, street, city, state) values (109, '3 Longview Circle', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (110, '9836 Center Point', 'Amarillo', 'TX');
insert into address (addrId, street, city, state) values (111, '4 Welch Alley', 'Bethlehem', 'PA');
insert into address (addrId, street, city, state) values (112, '9316 Buena Vista Lane', 'Denton', 'TX');
insert into address (addrId, street, city, state) values (113, '5342 Thompson Lane', 'Tacoma', 'WA');
insert into address (addrId, street, city, state) values (114, '6 Armistice Drive', 'Richmond', 'VA');
insert into address (addrId, street, city, state) values (115, '42 Rigney Trail', 'Van Nuys', 'CA');
insert into address (addrId, street, city, state) values (116, '8984 Mcguire Lane', 'Decatur', 'GA');
insert into address (addrId, street, city, state) values (117, '9 Susan Avenue', 'Miami', 'FL');
insert into address (addrId, street, city, state) values (118, '7355 Lakeland Court', 'Los Angeles', 'CA');
insert into address (addrId, street, city, state) values (119, '592 Atwood Hill', 'Salt Lake City', 'UT');
insert into address (addrId, street, city, state) values (120, '434 Westerfield Drive', 'Rochester', 'NY');
insert into address (addrId, street, city, state) values (121, '835 Coolidge Circle', 'Toledo', 'OH');
insert into address (addrId, street, city, state) values (122, '849 Mallory Alley', 'Chicago', 'IL');
insert into address (addrId, street, city, state) values (123, '69 Karstens Park', 'Springfield', 'IL');
insert into address (addrId, street, city, state) values (124, '543 Florence Parkway', 'Lubbock', 'TX');
insert into address (addrId, street, city, state) values (125, '758 Lake View Lane', 'Springfield', 'MA');
insert into address (addrId, street, city, state) values (126, '405 1st Trail', 'New York City', 'NY');
insert into address (addrId, street, city, state) values (127, '4 Butterfield Drive', 'El Paso', 'TX');
insert into address (addrId, street, city, state) values (128, '2 Grasskamp Parkway', 'Cedar Rapids', 'IA');
insert into address (addrId, street, city, state) values (129, '4294 Porter Junction', 'Lincoln', 'NE');
insert into address (addrId, street, city, state) values (130, '90 Springview Way', 'Des Moines', 'IA');
insert into address (addrId, street, city, state) values (131, '762 Hoffman Place', 'Clearwater', 'FL');
insert into address (addrId, street, city, state) values (132, '57 American Ash Terrace', 'New York City', 'NY');
insert into address (addrId, street, city, state) values (133, '9 Elmside Crossing', 'Toledo', 'OH');
insert into address (addrId, street, city, state) values (134, '6 Towne Road', 'Jacksonville', 'FL');
insert into address (addrId, street, city, state) values (135, '0940 Mcguire Plaza', 'Brooklyn', 'NY');
insert into address (addrId, street, city, state) values (136, '6497 Holy Cross Center', 'Pittsburgh', 'PA');
insert into address (addrId, street, city, state) values (137, '421 North Crossing', 'Tampa', 'FL');
insert into address (addrId, street, city, state) values (138, '0 Stoughton Crossing', 'Brea', 'CA');
insert into address (addrId, street, city, state) values (139, '3727 Corscot Circle', 'Albuquerque', 'NM');
insert into address (addrId, street, city, state) values (140, '4 Thierer Alley', 'Baton Rouge', 'LA');
insert into address (addrId, street, city, state) values (141, '89145 Center Drive', 'Memphis', 'TN');
insert into address (addrId, street, city, state) values (142, '700 Sauthoff Crossing', 'Washington', 'DC');
insert into address (addrId, street, city, state) values (143, '6 Arapahoe Junction', 'Frederick', 'MD');
insert into address (addrId, street, city, state) values (144, '8 Shasta Junction', 'Cleveland', 'OH');
insert into address (addrId, street, city, state) values (145, '7 Bashford Place', 'Trenton', 'NJ');
insert into address (addrId, street, city, state) values (146, '8536 Dwight Court', 'Detroit', 'MI');
insert into address (addrId, street, city, state) values (147, '29991 Fordem Trail', 'Detroit', 'MI');
insert into address (addrId, street, city, state) values (148, '295 Gale Drive', 'San Francisco', 'CA');
insert into address (addrId, street, city, state) values (149, '14 Sullivan Road', 'Fort Myers', 'FL');
insert into address (addrId, street, city, state) values (150, '9215 Ridgeway Circle', 'Kansas City', 'MO');
insert into address (addrId, street, city, state) values (151, '747 Westend Center', 'Springfield', 'MA');
insert into address (addrId, street, city, state) values (152, '163 Nelson Junction', 'Lubbock', 'TX');
insert into address (addrId, street, city, state) values (153, '0 Gateway Way', 'Pittsburgh', 'PA');
insert into address (addrId, street, city, state) values (154, '34 Moland Drive', 'Sioux City', 'IA');
insert into address (addrId, street, city, state) values (155, '88 Independence Street', 'Wilkes Barre', 'PA');
insert into address (addrId, street, city, state) values (156, '93800 Straubel Park', 'Riverside', 'CA');
insert into address (addrId, street, city, state) values (157, '35230 Garrison Crossing', 'Columbus', 'OH');
insert into address (addrId, street, city, state) values (158, '640 Algoma Center', 'Ogden', 'UT');
insert into address (addrId, street, city, state) values (159, '8504 Packers Terrace', 'Jefferson City', 'MO');
insert into address (addrId, street, city, state) values (160, '40695 Badeau Junction', 'Shawnee Mission', 'KS');
insert into address (addrId, street, city, state) values (161, '8 Basil Road', 'Birmingham', 'AL');
insert into address (addrId, street, city, state) values (162, '224 Westerfield Lane', 'Woburn', 'MA');
insert into address (addrId, street, city, state) values (163, '78113 Fairfield Alley', 'Anchorage', 'AK');
insert into address (addrId, street, city, state) values (164, '9 Duke Crossing', 'Camden', 'NJ');
insert into address (addrId, street, city, state) values (165, '987 Moland Terrace', 'Winston Salem', 'NC');
insert into address (addrId, street, city, state) values (166, '67115 Donald Terrace', 'Jacksonville', 'FL');
insert into address (addrId, street, city, state) values (167, '1067 Ludington Road', 'Memphis', 'TN');
insert into address (addrId, street, city, state) values (168, '84 Oxford Center', 'Hartford', 'CT');
insert into address (addrId, street, city, state) values (169, '443 Havey Alley', 'Charlotte', 'NC');
insert into address (addrId, street, city, state) values (170, '4788 Warner Hill', 'San Antonio', 'TX');
insert into address (addrId, street, city, state) values (171, '366 Buhler Crossing', 'Knoxville', 'TN');
insert into address (addrId, street, city, state) values (172, '3998 Forest Run Alley', 'Charlotte', 'NC');
insert into address (addrId, street, city, state) values (173, '394 Morningstar Trail', 'Santa Ana', 'CA');
insert into address (addrId, street, city, state) values (174, '947 Bay Plaza', 'Dallas', 'TX');
insert into address (addrId, street, city, state) values (175, '9 Ruskin Place', 'Conroe', 'TX');
insert into address (addrId, street, city, state) values (176, '705 Delaware Court', 'Portsmouth', 'NH');
insert into address (addrId, street, city, state) values (177, '9173 Everett Drive', 'Naples', 'FL');
insert into address (addrId, street, city, state) values (178, '2896 Fordem Terrace', 'Hyattsville', 'MD');
insert into address (addrId, street, city, state) values (179, '98 Ryan Way', 'Minneapolis', 'MN');
insert into address (addrId, street, city, state) values (180, '807 Kenwood Circle', 'Akron', 'OH');
insert into address (addrId, street, city, state) values (181, '58241 Esch Point', 'Miami', 'FL');
insert into address (addrId, street, city, state) values (182, '39 Hauk Place', 'Toledo', 'OH');
insert into address (addrId, street, city, state) values (183, '5941 Eastwood Place', 'Sarasota', 'FL');
insert into address (addrId, street, city, state) values (184, '91936 Oneill Way', 'Cincinnati', 'OH');
insert into address (addrId, street, city, state) values (185, '26274 North Court', 'Salt Lake City', 'UT');
insert into address (addrId, street, city, state) values (186, '4 Mayer Court', 'Albuquerque', 'NM');
insert into address (addrId, street, city, state) values (187, '0 7th Alley', 'Orlando', 'FL');
insert into address (addrId, street, city, state) values (188, '5109 Aberg Terrace', 'Delray Beach', 'FL');
insert into address (addrId, street, city, state) values (189, '164 Novick Drive', 'Saint Cloud', 'MN');
insert into address (addrId, street, city, state) values (190, '76 Quincy Court', 'Monticello', 'MN');
insert into address (addrId, street, city, state) values (191, '9 Barby Street', 'Aiken', 'SC');
insert into address (addrId, street, city, state) values (192, '38 Steensland Trail', 'Tampa', 'FL');
insert into address (addrId, street, city, state) values (193, '4720 Evergreen Plaza', 'Sioux Falls', 'SD');
insert into address (addrId, street, city, state) values (194, '28 Fisk Street', 'Arlington', 'VA');
insert into address (addrId, street, city, state) values (195, '05 Carey Street', 'Bethesda', 'MD');
insert into address (addrId, street, city, state) values (196, '94436 Pennsylvania Trail', 'Meridian', 'MS');
insert into address (addrId, street, city, state) values (197, '3 Barnett Lane', 'Chicago', 'IL');
insert into address (addrId, street, city, state) values (198, '516 Schurz Way', 'Humble', 'TX');
insert into address (addrId, street, city, state) values (199, '0006 Waubesa Parkway', 'El Paso', 'TX');
insert into address (addrId, street, city, state) values (200, '52907 Huxley Hill', 'Salem', 'OR');
